spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
            
  application:
    name: api-gateway
    
server:
  port: 9097
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
